### ISSUE TITLE
resolve glibc issue

### ISSUE THREAD

**Issue by star-buck** [opendesktop/opendesktop-app#19]
Opendesktop AppImage doesnt install any items when used on Manjaro KDE.

**Comment by akiraohgaki** [comment]
Related: https://github.com/opendesktop/opendesktop-app/issues/8#issuecomment-352853781

**Comment by star-buck** [comment]
@probono: any idea how to solve this?

**Comment by akiraohgaki** [comment]
On Manjaro, I got relocation error to libk5crypto.so.3.

**Comment by probonopd** [comment]
The application launches on `ubuntustudio-16.04.3-dvd-amd64.iso`.

When I __close__ the application then I see on the command line:

```
me@host:~$ Downloads/opendesktop-app-3.0.0-1-x86_64.AppImage 
{ Error: Command failed: /tmp/.mount_opendekNqZnV/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152
Websocket server started at: "ws://127.0.0.1:49152"

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/tmp/.mount_opendekNqZnV/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152' }
```

This may be unrelated to the issue here.

So I will need to try on Manjaro and see if I can reproduce the issue there.

**Comment by star-buck** [comment]
What exactly could be an issue with glibc there?

**Comment by probonopd** [comment]
> On Manjaro, I got relocation error of libk5crypto.so.3.

Can you please paste the whole error message @akiraohgaki?

**Comment by probonopd** [comment]
This is what I get on `antergos-2014.08.07-x86_64.iso` - is this similar to the Manjaro error?

```
[antergos@Antergos-ISO ~]$ '/home/antergos/Downloads/opendesktop-app-3.0.0-1-x86_64.AppImage' 
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/opendesktop-app: /usr/lib/libdbus-1.so.3: no version information available (required by /tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/libgconf-2.so.4)
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/opendesktop-app: /usr/lib/libdbus-1.so.3: no version information available (required by /tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/libgconf-2.so.4)
{ Error: Command failed: /tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by /tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager)
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager)
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_ocs-mals5P22/usr/bin/../lib/libproxy.so.1)
/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager: /usr/lib/libgpg-error.so.0: no version information available (required by /tmp/.mount_ocs-mals5P22/usr/bin/../lib/libgcrypt.so.20)

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/tmp/.mount_opender0dN78/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152' }
```

It means that `ocs-manager` was built on a system with a newer glibc than on `antergos-2014.08.07-x86_64.iso`.

Which system did you build `ocs-manager` on? I recommend to build on Ubuntu 14.04 LTS (trusty) or older.

**Comment by probonopd** [comment]
May be related to https://github.com/opendesktop/opendesktop-app/commit/43b57d7e7e7ab1754780d2d7e931adb7b701b7f3

**Comment by probonopd** [comment]
On `manjaro-xfce-17.1.1-stable-x86_64.iso` getting:

```
[manjaro@manjaro ~]$ Downloads/opendesktop-app-3.0.0-1-x86_64.AppImage 
{ Error: Command failed: /tmp/.mount_opendeLuHmyL/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152
/tmp/.mount_opendeLuHmyL/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager: relocation error: /usr/lib/libk5crypto.so.3: symbol k5_os_mutex_destroy, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/tmp/.mount_opendeLuHmyL/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 49152' }
```

**Comment by probonopd** [comment]
Further debugging:

```
# Extract the AppImage
./opendesktop-app-3.0.0-1-x86_64.AppImage --appimage-extract

# Extract the AppImage in the AppImage
mv squashfs-root/ AppImage
./AppImage/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager --appimage-extract

# Check the dependencies on the system
ldd squashfs-root/usr/bin/ocs-manager | cut -d " " -f 3 | grep ^/usr
/usr/lib/libpthread.so.0
/usr/lib/libstdc++.so.6
/usr/lib/libgcc_s.so.1
/usr/lib/libc.so.6
/usr/lib/fglrx/libGL.so.1
/usr/lib/libm.so.6
/usr/lib/libdl.so.2
/usr/lib/libglib-2.0.so.0
/usr/lib/librt.so.1
/usr/lib64/ld-linux-x86-64.so.2
/usr/lib/libp11-kit.so.0
/usr/lib/libk5crypto.so.3 ### <---- this one seems to be problematic
/usr/lib/libcom_err.so.2
/usr/lib/libresolv.so.2
/usr/lib/libXext.so.6
/usr/lib/libpcre.so.1
/usr/lib/libffi.so.6
/usr/lib/libkeyutils.so.1
/usr/lib/libX11.so.6
/usr/lib/libcrypt.so.1
/usr/lib/libxcb.so.1
/usr/lib/libgpg-error.so.0
/usr/lib/libXau.so.6
/usr/lib/libXdmcp.so.6
```

**Comment by probonopd** [comment]
@TheAssassin wrote [here](https://github.com/desktop/dugite-native/issues/42#issuecomment-352253495):

> Since libcurl is built to support a variety of protocols, it can be annoying to have to bundle all those libraries as well. Also, as part of the series https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues, the CA chain is located in different places on all platforms. libcurl solves the issue by having the user specify the location on configure time. To fix this issue and also reduce the amount of dependencies, I started to build my own packages on OBS, based on the Debian ones, patched to support only HTTP(S) and search for the certificate location on runtime.
> 
> Check out https://build.opensuse.org/package/show/home:TheAssassin:AppImageLibraries/curl-httponly. Use like https://github.com/AppImage/AppImageUpdate/blob/rewrite/resources/bootstrap-container.sh#L8-L10. The packages should upgrade fine on Debian based systems. The package has been forked from the latest available unstable package.

**Comment by akiraohgaki** [comment]
OK, I will change build platform, and bundle libcurl-gnutls.so.4. @probonopd Thanks a lot.

**Comment by probonopd** [comment]
Thanks @akiraohgaki - it is important that you bundle not the default `libcurl-gnutls.so.4` but a special one that does not depend on Kerberos, like the one from @TheAssassin from https://download.opensuse.org/repositories/home:/TheAssassin:/AppImageLibraries/xUbuntu_14.04/amd64/.

**Comment by star-buck** [comment]
@akiraohgaki : any success?

**Comment by akiraohgaki** [comment]
Fixed.

This one should work without libcurl-gnutls.so.4 error, also built with ubuntu 14.04.
https://transfer.sh/obyiP/opendesktop-app-3.0.0-1-x86_64.AppImage

**Comment by probonopd** [comment]
@akiraohgaki I successfully ran it on `ubuntu-14.04.1-desktop-amd64.iso` and installed an AppImage with it. Thank you.

**Comment by probonopd** [comment]
Also running great on netrunner-desktop-1703-64bit.iso:

![](https://user-images.githubusercontent.com/2480569/35168060-8841053c-fd4f-11e7-8c82-ce6a015c9c32.png)

**Comment by star-buck** [comment]
@akiraohgaki @probonopd 
It seems latest 3.0.1 AppImage still doesnt work on KDE Neon:
https://github.com/opendesktop/opendesktop-app/issues/22

**Comment by TheAssassin** [comment]
@star-buck are you sure #22 is related? I don't see the relation to this issue, actually, the "type error" 

Also, it doesn't seem like @akiraohgaki has pushed a change to this repository, he just posted a link to a seemingly working AppImage. I suppose this was on purpose, to get some feedback before publishing a new release. If both issues are related, maybe we should forward the link to the new AppImage to #22, and ask them to retry with this one.

**Comment by star-buck** [comment]
So what was glibc about?
My initial comment was about the same issue of not being able to install somehting from within the app, so I thought glibc was what cuased it, but dont know.

**Comment by TheAssassin** [comment]
It was a library issue as far as I can tell. There's been issues with libcurl and libssl, but it seems like @akiraohgaki fixed them. The error messages were different than what has been reported in #22 (that bug report actually lacks quite some information, like a full error message, etc.).

**Comment by akiraohgaki** [comment]
@star-buck 
Already we solved glibc issue by build platform changed.
Also we solved curl and ssl library issue.

**Comment by probonopd** [comment]
Is there still an issue remaining that needs to be solved, or does it work successfully now for everyone?
